server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: zuul-1
    prefer-ip-address: true

spring:
  application:
    name: zuul

zuul:
  prefix: /api
  strip-prefix: false
  ignored-services: "*"
  routes:
    power:
      serviceId: server-power
      path: /power/**
    order:
      serviceId: server-order
      path: /order/**